language: node_js
node_js:
- 11
addons:
  apt:
    packages:
    - libgconf-2-4
cache:
  directories:
  - "~/.cache"
env:
- CYPRESS_TRAVIS=true
install:
- npm ci
script:
- npm run db:up && npm run db:seed
- npm test
deploy:
  provider: heroku
  api_key:
    secure: 4c7cc75b-ea0f-40e0-8564-b99e932656fd
  app: beer-shop
  on:
    repo: gmalicky/beer-shop
