language: node_js
node_js:
- 11
addons:
  apt:
    packages:
    - libgconf-2-4
cache:
  directories:
  - "~/.cache"
env:
- CYPRESS_TRAVIS=true
install:
- npm ci
script:
- npm run db:up && npm run db:seed
- npm test
deploy:
  provider: heroku
  api_key:
    secure: yDMuMW1gT7VIeJ5tNy6JnKQLZtoFybw106HG9ksRhf5jcGqRl89z9uEYH8pNX5Jy0AYWXPTQhsNQMm1mkPWmc0jlU0Qa7qjn3r3+Tew9vzvNVXl+DHpGbpMB5S+HO3l7IhRHyfSBB4FpWq/dDvXpi+D4v4tTqAG2/Ovwl5AjxmM5Wimm0tg0K2FR10sDrmvTm/TQvfx0A2qPUvu6IdNE8Br8D6+DHjNIAfVUdTdl0eMerfcLXK+Bg5tsh2myrTB66k3oHCznHOW9uX4FurrkGYY3/ZGFJznG1tEPWBI/za0FvwI/SmxtmLCDvgl8NntnK+l3KvU0JtUuDGYGylwUu2DC05OiFh6soh0pAIedrzLJ261tNPTisVki/x1rz4qhPMloUd5JICPXa6oHxK8IuSrBwm6JrQdKq/SDCg9T6atxOnJ3hP0Ae/kDjw5f3yl9bvORsRvYVlQwx2I8UrYg4jYfwVTe1qjQDdtizs/Nz/xao6tYaqy1X1yEIqEZY+23TElgAC5WbtvuW1NXMV1I2g2i/tpJIZ1i9KpFyy4eBzVErRB8GBviNaOM/HItRQBuI95edI3xuVIQrQj7M2Aiec29O5e9fd0LWMEMjmJWDb0p79e9E0ebin+Jq5VqARI27ii6GBvC9Et1IUc+mWX2HY/dPnGNni5Vec2qibPrbPk=
  app: beer-shop
  on:
    repo: gmalicky/beer-shop
