language: node_js
node_js:
  - 11
addons:
  apt:
    packages:
      # Ubuntu 16+ does not install this dependency by default, so we need to install it ourselves
      - libgconf-2-4
cache:
  directories:
    - ~/.cache
env:
  - CYPRESS_TRAVIS=true
  - CYPRESS_PATH=process.env.PATH
install:
  - npm ci
script:
  - npm run db:up && npm run db:seed
  - npm test